config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'


  resource :dashboard, only: [:show]

  get '/jeremie', to: 'pages#jeremie', as: 'jeremie'
  get '/maxime', to: 'pages#maxime', as: 'maxime'
  get '/nicolas', to: 'pages#nicolas', as: 'nicolas'

  post '/instruments', to: 'instruments#index', as: 'intruments'

  resources :musical_works, only: [:index, :show, :create] do
    # :new, :create, , :detroy , :edit, :update
    resources :work_instruments, only: [:create] do
      collection do
        post :load_orchestra_composition
      end
    end
    # pas d'index. La liste se fait sur la show d'un musical work
    # pas de show. L'affichage se fait uniquement en liste
    # pas de new. On fait un :create directement depuis un musical_works
    # pas d'edit, la modif se fait en ajax via la liste visible dans le musical work.
  end
  resources :work_instruments, only: [:update, :destroy]

  resources :invitations, only: [:index, :create, :show] do
  # pas de new, on a un formulaire de creation affiché dans l'index
  # pas d'edit, on va juste modifier certains champs via des routes 'member'
  # pas d'update, idem
  # pas de destroy, on ne peut pas supprimer une invitation.
    member do
      patch :accept
      patch :decline
      patch :send_email
    end
  end

  # TO add : url of the SendinBlue API to change the invitation deliver/read/error

  resources :concerts, only: [:index, :show, :update] do
  # pas de edit, la modif se fait en ajax dans la show.
  # plus tard :new, :create, :destroy
    resources :program_steps, only: [:update, :destroy] do
    # pas index :
    # pas show
    # pas new
    # pas edit
      collection do
        post :add_work
        post :add_intermission
      end
    end

  end

  resources :orchestra_compositions, only: [:create]
  # pas de new : la création se fait dans l'interface d'un musical_work
  # pas de edit : la modif du se fait dans l'index
  # pas de show : toutes les infos sont dans l'index
  # plus tard : :index, :destroy



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %> <img src="close.soon" style="display:none;" onerror="(function(el){ setTimeout(function(){ el.parentNode.parentNode.removeChild(el.parentNode); },2000 ); })(this);" />
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %> <img src="close.soon" style="display:none;" onerror="(function(el){ setTimeout(function(){ el.parentNode.parentNode.removeChild(el.parentNode); },2000 ); })(this);" />
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_invitation.html.erb
<div class='box invitation'>
  <div class='action_buttons'>
    <% if invitation.status == "pending" %>
      <%= link_to '', accept_invitation_path(invitation), method: :patch, class: "btn-validate"%>
      <%= link_to '', decline_invitation_path(invitation), method: :patch, class: "btn-decline"%>
    <% elsif invitation.status == "accepted" %>
      <span class="icon icon-validate green"></span>
    <% elsif invitation.status == "rejected" %>
      <span class="icon icon-decline orange"></span>
    <% end %>
    <div class='description'>
      <%= link_to invitation_path(invitation) do %>
        <%= invitation.full_name %> - <span><%= invitation.instrument.name %></span>
      <% end %>
    </div>
  </div>
  <div class='action_buttons'>
    <% enveloppe_class = "icon icon_size icon-envelope" %>
    <% open_class = "icon icon_size  icon-open-envelope" %>
    <% click_class = "icon icon_size icon-click" %>
    <% title_deliver = "Email sent" %>
    <% title_open = "" %>
    <% title_click = "" %>

    <% if invitation.email_bounce %>
      <% enveloppe_class += " orange" %>
      <% title_deliver = "Error. Email not received"%>
    <% else %>
      <% if invitation.email_delivered %>
        <% enveloppe_class += " green" %>
        <% title_deliver = "Email delivered"%>
      <% else %>
        <% enveloppe_class += " gray" %>
        <% title_deliver = "Sending email... processing"%>
      <% end %>
    <% end %>
    <% if invitation.email_read %>
      <% open_class += " green" %>
      <% title_open = "Recipient has opened the email"%>
    <% else %>
      <% open_class += " gray" %>
      <% title_open = "Email not opened yet"%>
    <% end %>
    <% if invitation.email_clicked %>
      <% click_class += " green" %>
      <% title_click = "Recipient clicked on a link"%>
    <% else %>
      <% click_class += " gray" %>
      <% title_click = "Recipient has not clicked for now."%>
    <% end %>
    <span class="<%= enveloppe_class%>" data-placement="top" data-toggle="tooltip" title="<%= title_deliver %>"></span>
    <span class="<%= open_class%>" title="<%= title_open %>" ></span>
    <span class="<%= click_class%>" title="<%= title_click %>"></span>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% on_landing = params[:controller] == "pages" && params[:action] == "landing" %>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <% if user_signed_in? %>
    <% home_url = dashboard_path %>
  <% else %>
    <% home_url = root_path %>
  <% end %>
  <%= link_to home_url, class: "navbar-brand" do %>
    <%= image_tag "final_logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Concerts", concerts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Musical Works", musical_works_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Invitations", invitations_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <div class="nav-item nav-item-right">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <% unless on_landing %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_program_step.html.erb
<% if program_step.kind == "intermission" %>
  <div
    class="box intermission"
    data-patch-url="<%= concert_program_step_path(program_step.concert.id, program_step.id) %>">
    <span class="icon icon-pause"></span>
    <span class="text">Intermission</span>
    <span class="duration">10 min</span>
<% else %>
  <div class="box program-step" data-patch-url="<%= concert_program_step_path(program_step.concert.id, program_step.id) %>">
    <div class="icon icon-drag"></div>
    <div class="composer"><%= program_step.musical_work.composer_name %></div>
    <div class="work-infos">
      <p><%= program_step.musical_work.title %></p>
      <% if program_step.musical_work.work_instruments.empty? %>
        <%= link_to musical_work_path(program_step.musical_work), class: 'orange' do %>
          Missing all instruments
        <% end %>
      <% end %>
      <% if program_step.musical_work.missing_sheets.any? %>
        <p><%= link_to musical_work_path(program_step.musical_work), class: 'orange' do %>
            Missing <%= program_step.musical_work.missing_sheets.map(&:inspect).join(', ').tr('"', '') %> sheets
          <% end %>
        </p>
      <% end %>
    </div>
    <div class="duration"><%= program_step.musical_work.duration %> min</div>
  <% end %>
    <div class="trash"><%= link_to "", concert_program_step_path(program_step.concert, program_step), { method: "delete", data: { confirm: "Are you sure?" }, class: 'icon icon-trash' } %></div>
  </div>

app/views/shared/_title.html.erb
  <script language=javascript>
    var rev = "fwd";
    function titlebar(val){
        var msg  = "Welcome to My Orchestraa";
        var res = " ";
        var speed = 120;
        var pos = val;
        msg = ""+msg+"";
        var le = msg.length;
        if(rev == "fwd"){
            if(pos < le){
                pos = pos+1;
                scroll = msg.substr(0,pos);
                document.title = scroll;
                timer = window.setTimeout("titlebar("+pos+")",speed);
            }
            else {
                rev = "bwd";
                timer = window.setTimeout("titlebar("+pos+")",speed);
            }
        }
        else {
            if(pos > 0) {
                pos = pos-1;
                var ale = le-pos;
                scrol = msg.substr(ale,le);
                document.title = scrol;
                timer = window.setTimeout("titlebar("+pos+")",speed);
            }
            else {
                rev = "fwd";
                timer = window.setTimeout("titlebar("+pos+")",speed);
            }
        }
    }
    titlebar(0);
</script>

app/views/shared/_work_instrument.html.erb
<div class="col-6">
  <div class="box work-box">
    <h2><span class="icon icon-<%= icon %>"></span><span><%= category %></span></h2>
    <div class="main-box">
      <div class="edit-box">
        <% work_instruments.each do |work_instrument| %>
          <div class="edit-line">
            <%= simple_form_for(work_instrument) do |f| %>
              <!-- <input type="number" placeholder="0" class="input-box" value="<%= work_instrument.quantity %>"> -->
              <%= f.input :quantity, label:false %>
              <p class="edit-instrument"><%= work_instrument.instrument.name %></p>
              <% if work_instrument.sheet_pdf.url.nil? %>
                <div class="upload-pdf">
                  <%= f.input :sheet_pdf, label: 'Select missing pdf', input_html: {id: "work_instrument_sheet_pdf_#{work_instrument.id}" }, label_html: { class: 'label-pdf orange' } %>
                  <%= f.input :sheet_pdf_cache, input_html: {id: "work_instrument_sheet_pdf_#{work_instrument.id}_cache"}, as: :hidden %>
                </div>
              <% else %>
                <%= link_to "", work_instrument.sheet_pdf.url, target: "_blank", class: "icon icon-read-mail eye-view-sheet" %>
                <%= link_to "View PDF", work_instrument.sheet_pdf.url, target: "_blank" %>
              <% end %>
              <%= f.button :submit, "Save", class: 'save green' %>
          <% end %>
          </div>
        <% end %>
        <div class="add-instrument">
          <form action="<%= musical_work_work_instruments_path(@musical_work) %>" method="post">
            <select onchange="this.form.submit()" name="work_instrument[instrument_id]" id="instrument-selector" class="button-selector">
              <option value="add-instrument">Add instrument </option>
              <% Instrument.where(category: category).each do |instr|  %>
                <option value="<%= instr.id %>"><%= instr.name %></option>
              <% end %>
            </select>
            <input type="hidden" name="authenticity_token" id="authenticity_token" value="<%= form_authenticity_token %>" />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>