config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'


  resource :dashboard, only: [:show]

  get '/jeremie', to: 'pages#jeremie', as: 'jeremie'
  get '/maxime', to: 'pages#maxime', as: 'maxime'
  get '/nicolas', to: 'pages#nicolas', as: 'nicolas'

  post '/instruments', to: 'instruments#index', as: 'intruments'

  resources :musical_works, only: [:index, :show, :create] do
    # :new, :create, , :detroy , :edit, :update
    resources :work_instruments, only: [:create] do
      collection do
        post :load_orchestra_composition
      end
    end
    # pas d'index. La liste se fait sur la show d'un musical work
    # pas de show. L'affichage se fait uniquement en liste
    # pas de new. On fait un :create directement depuis un musical_works
    # pas d'edit, la modif se fait en ajax via la liste visible dans le musical work.
  end
  resources :work_instruments, only: [:update, :destroy]

  resources :invitations, only: [:index, :create, :show] do
  # pas de new, on a un formulaire de creation affiché dans l'index
  # pas d'edit, on va juste modifier certains champs via des routes 'member'
  # pas d'update, idem
  # pas de destroy, on ne peut pas supprimer une invitation.
    member do
      patch :accept
      patch :decline
      patch :send_email
    end
  end

  # TO add : url of the SendinBlue API to change the invitation deliver/read/error

  resources :concerts, only: [:index, :show, :update] do
  # pas de edit, la modif se fait en ajax dans la show.
  # plus tard :new, :create, :destroy
    resources :program_steps, only: [:update, :destroy] do
    # pas index :
    # pas show
    # pas new
    # pas edit
      collection do
        post :add_work
        post :add_intermission
      end
    end

  end

  resources :orchestra_compositions, only: [:create]
  # pas de new : la création se fait dans l'interface d'un musical_work
  # pas de edit : la modif du se fait dans l'index
  # pas de show : toutes les infos sont dans l'index
  # plus tard : :index, :destroy



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/concert.rb
class Concert < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :program_steps, dependent: :destroy

  validates :name, presence: true

  validates :start_at, presence: { message: 'Must be a valid date' }
  validates :end_at, presence: { message: 'Must be a valid date' }
  validate :start_must_be_before_end

  private

  def start_must_be_before_end
    errors.add(:start_at, "must be before end time") unless
        start_at < end_at
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index
    @concerts = current_user.concerts.geocoded
  end

  def show
    @concert = Concert.find(params[:id])
    @program_steps = @concert.program_steps.order(position: :asc)
    @markers = []
    @markers.push(
      {
        lat: @concert.latitude,
        lng: @concert.longitude,
        # infoWindow: render_to_string(partial: "info_window", locals: { concert: concert }),
        image_url: helpers.asset_url('marker_map.svg')
      })
  end

  def update
  end

end

app/views/concerts/index.html.erb
<h1 class="concert-title">Concerts</h1>
<div class="index-concert-works">
  <% @concerts.each do |concert|%>
    <ul>
  <div class="box">
      <li><h2> <%= concert.name %></h2></li>
      <li class="icon icon-concert"> <%= concert.location %></li>
      <li class="icon icon-location"> <%= concert.address %></li>
      <%= link_to "View concert details", concert_path(concert)%>
    </ul>
  <% end %>
  </div>
</div>

app/views/concerts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-3">
      <div class="box">
        <h1 class="mb-4"><%= @concert.name %></h1>
        <div class="infos-concert">
          <div class="info-icon icon icon-agenda"></div>
          <div class="date-infos">
            <p><%= @concert.start_at.strftime("%d %B %Y") %></p>
            <p class="lower"><%= @concert.start_at.strftime("%H:%M")%><%= @concert.end_at.strftime(" to %H:%M") %></p>
          </div>
        </div>
        <div class="infos-concert">
          <div class="info-icon icon icon-location"></div>
          <div class="adress-infos">
            <p><%= @concert.location %></p>
            <p class="lower"><%= @concert.address %></p>
          </div>
        </div>
        <div class="infos-concert">
          <div class="info-icon icon icon-note"></div>
          <div class="notes-infos">
            <p><%= @concert.notes %></p>
          </div>
        </div>
      </div>
      <div class="box" id="map"
        style="width: 100%;
        height: 400px; padding: 0px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class="col-12 col-lg-9">
      <div class="box dark_box program">
        <h2>Program</h2>
          <div class="banner_button infos-concert program">
            <div id="add-program-steps">

              <form action="<%= add_work_concert_program_steps_path(@concert) %>" method="post">
                <select onchange="this.form.submit()" name="work_id" id="work-selector" class="button-selector">
                  <option value="add-work">- Add musical work -</option>
                  <% MusicalWork.all.each do |work|  %>
                    <option value="<%= work.id %>"><%= work.title %></option>
                  <% end %>
                </select>
                <input type="hidden" name="authenticity_token" id="authenticity_token" value="<%= form_authenticity_token %>" />
              </form>
            </div>
            <div id="add-intermission">
              <div>
                <%= link_to add_intermission_concert_program_steps_path(@concert), method: "post" do %>
                  <span class="btn add_button"><span class="icon icon-plus"></span><span>Add intermission</span></span>
                <% end %>
              </div>
            </div>
          </div>
          <div id="program-steps">
            <% @program_steps.each do |program_step| %>
              <%= render partial: 'shared/program_step', locals: {program_step: program_step } %>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/concerts/update.html.erb
<h1>Concerts#update</h1>
<p>Find me in app/views/concerts/update.html.erb</p>