config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'


  resource :dashboard, only: [:show]

  get '/jeremie', to: 'pages#jeremie', as: 'jeremie'
  get '/maxime', to: 'pages#maxime', as: 'maxime'
  get '/nicolas', to: 'pages#nicolas', as: 'nicolas'

  post '/instruments', to: 'instruments#index', as: 'intruments'

  resources :musical_works, only: [:index, :show, :create] do
    # :new, :create, , :detroy , :edit, :update
    resources :work_instruments, only: [:create] do
      collection do
        post :load_orchestra_composition
      end
    end
    # pas d'index. La liste se fait sur la show d'un musical work
    # pas de show. L'affichage se fait uniquement en liste
    # pas de new. On fait un :create directement depuis un musical_works
    # pas d'edit, la modif se fait en ajax via la liste visible dans le musical work.
  end
  resources :work_instruments, only: [:update, :destroy]

  resources :invitations, only: [:index, :create, :show] do
  # pas de new, on a un formulaire de creation affiché dans l'index
  # pas d'edit, on va juste modifier certains champs via des routes 'member'
  # pas d'update, idem
  # pas de destroy, on ne peut pas supprimer une invitation.
    member do
      patch :accept
      patch :decline
      patch :send_email
    end
  end

  # TO add : url of the SendinBlue API to change the invitation deliver/read/error

  resources :concerts, only: [:index, :show, :update] do
  # pas de edit, la modif se fait en ajax dans la show.
  # plus tard :new, :create, :destroy
    resources :program_steps, only: [:update, :destroy] do
    # pas index :
    # pas show
    # pas new
    # pas edit
      collection do
        post :add_work
        post :add_intermission
      end
    end

  end

  resources :orchestra_compositions, only: [:create]
  # pas de new : la création se fait dans l'interface d'un musical_work
  # pas de edit : la modif du se fait dans l'index
  # pas de show : toutes les infos sont dans l'index
  # plus tard : :index, :destroy



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/musical_work.rb
class MusicalWork < ApplicationRecord
  belongs_to :user
  # has_many :program_steps
  has_many :work_instruments, dependent: :destroy

  validates :title, presence: true

  def missing_sheets
    instruments_list = []
    work_instruments = self.work_instruments
    work_instruments.each do |work_instr|
      unless work_instr.sheet_pdf.url
        instruments_list << work_instr.instrument.name
      end
    end
    return instruments_list
  end
end

app/controllers/musical_works_controller.rb
class MusicalWorksController < ApplicationController
  def index
    @musical_works = current_user.musical_works
  end

  def show
    $instrument_categories = ["Strings","Brass","Woodwinds","Percussions","Keyboards"]

    @musical_work = MusicalWork.find(params[:id])
    @work_instruments = generate_instruments_hash
    @missing_categories = missing_categories
    @orchestra_compositions = OrchestraComposition.all
  end

  def create
    @musical_work = MusicalWork.create(
      user: current_user,
      title: 'New ',
      composer_name: 'Bethoveen',
      duration: 45,
      notes: ""
    )
    redirect_to musical_work_path(@musical_work)
  end

  private

  def generate_instruments_hash
    instruments = {
      "Strings" => [],
      "Brass" => [],
      "Woodwinds" => [],
      "Percussions" => [],
      "Keyboards" => []
    }
    work_instruments = @musical_work.work_instruments.joins(:instrument).order('instruments.position')
    work_instruments.each do |work_instr|
      instruments[work_instr.instrument.category] << work_instr
    end
    return instruments


    # {
    #   "Strings"=>[

    #     WorkInstrument id: 3116, musical_work_id: 2739, instrument_id: 2264, quantity: 4,
    #     WorkInstrument id: 3118, musical_work_id: 2739, instrument_id: 2265, quantity: 3,
    #     WorkInstrument id: 3122, musical_work_id: 2739, instrument_id: 2266, quantity: 2,
    #     WorkInstrument id: 3126, musical_work_id: 2739, instrument_id: 2268, quantity: 1,
    #   ],
    #     "Brass"=>[
    #     WorkInstrument id: 3120, musical_work_id: 2739, instrument_id: 2281, quantity: 2,,

    #     WorkInstrument id: 3123, musical_work_id: 2739, instrument_id: 2282, quantity: 2,
    #     WorkInstrument id: 3119, musical_work_id: 2739, instrument_id: 2285, quantity: 1,
    #   ],
    #     "Woodwinds"=>[
    #     WorkInstrument id: 3121, musical_work_id: 2739, instrument_id: 2270, quantity: 1,,
    #     WorkInstrument id: 3117, musical_work_id: 2739, instrument_id: 2273, quantity: 3,
    #   ],
    #     "Percussions"=>[
    #     WorkInstrument id: 3127, musical_work_id: 2739, instrument_id: 2289, quantity: 1,,
    #     WorkInstrument id: 3124, musical_work_id: 2739, instrument_id: 2290, quantity: 1,
    #   ],
    #     "Keyboards"=>[
    #     WorkInstrument id: 3125, musical_work_id: 2739, instrument_id: 2296, quantity: 1,
    #   ]
    # }

  end

  def missing_categories
    empty_categories = []
    @work_instruments.each do |category, instruments|
      empty_categories << category if instruments.empty?
    end
    return empty_categories
  end
end

app/views/musical_works/index.html.erb
<h1>Musical works</h1>
<div class="index-concert-works">
  <% @musical_works.each do |musical_work|%>
    <div class="box">
      <ul>
      <li><h2><%= musical_work.title %></h2></li>
      <li><%= musical_work.composer_name %></li>
      <li><%= musical_work.duration %> min.</li>
      <%= link_to "View musical work details", musical_work_path(musical_work)%>
      </ul>
    </div>
  <% end %>
  <%= link_to "add new musical work", musical_works_path, method: :post %>
</div>

app/views/musical_works/show.html.erb
<div class="col-md-12 musical-work-show">
  <div class="wrapper">
    <div class="work-card">
      <div class="front">
        <h1><%= @musical_work.title %></h1>
        <p><%= @musical_work.composer_name %><span><%= @musical_work.duration %> min.</span></p>
        <p class="note-work"><%= @musical_work.notes %></p>
      </div>
      <div class="right">
        <h2>Composition</h2>
        <ul>
          <li class="icon icon-strings compose-icon"> Strings x 10</li>
          <li class="icon icon-percussions compose-icon"> Percussion  x 2</li>
          <li class="icon icon-keyboards compose-icon"> Keyboard x1</li>
          <li class="icon icon-brass compose-icon"> Brass x5</li>
          <li class="icon icon-woodwinds compose-icon"> Woodwinds x 4</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="box dark_box work-edit col-9">
    <% Instrument::CATEGORIES.each do |category| %>
      <% if @work_instruments[category].any? %>
        <%= render partial: 'shared/work_instrument', locals: {icon: category.downcase, category: category, work_instruments: @work_instruments[category] } %>
      <% end %>
    <% end %>
    <% if @missing_categories.count == Instrument::CATEGORIES.count  %>
      <div class="col-6">
        <div class="box work-box add-template-box">
          <form action="<%= load_orchestra_composition_musical_work_work_instruments_path(@musical_work) %>" method="post">
            <select onchange="this.form.submit()" name="composition" id="composition-selector" class= "button-selector">
              <option value="select">Select composition</option>
              <% @orchestra_compositions.each do |composition| %>
                <option value="<%= composition.id %>" id="composition-selector-<%= composition.id %>"><%= composition.name %></option>
              <% end %>
            </select>
            <input type="hidden" name="authenticity_token" id="authenticity_token" value="<%= form_authenticity_token %>" />
          </form>
        </div>
      </div>
    <% end %>
    <% if @missing_categories.any? %>
      <div class="col-6">
          <div class="box work-box add-category-box">
            <!-- <form action="/instruments" accept-charset="UTF-8" data-remote="true" method="post">
              <select onchange="this.form.submit()" name="category" id="category-selector" class= "btn-category-selector">
            -->
              <select onchange="this.form.submit()" name="category" id="category-selector" class= "button-selector">
                <option value="add-category">Add category</option>
                <% @missing_categories.each do |category| %>
                  <option value="<%= category %>" id="category-selector"><%= category %></option>
                <% end %>
              </select>
              <!-- <input type="hidden" name="authenticity_token" id="authenticity_token" value="<%= form_authenticity_token %>" /> -->
            <!-- </form> -->
          </div>
      </div>
    <% end %>
  </div>
</div>